name: Comet
version: '${project.version}'
main: gg.aquatic.comet.ParticleEmitter
api-version: '1.19'
libraries:
  - org.openjdk.nashorn:nashorn-core:15.4
depend:
  - Waves

commands:
  fireparticle:
  explosionparticle:
  bloodparticle: