name: ParticleEmitter
version: '1.0-SNAPSHOT'
main: com.ixume.particleemitter.ParticleEmitter
api-version: '1.20'

commands:
  fireparticle:
  explosionparticle:
  bloodparticle:
  reloadparticles:
  offsettest: